"""initial_schema

Revision ID: 6f3695ef31c6
Revises: 
Create Date: 2026-06-09 00:21:28.262511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector  # noqa: F401 — needed for VECTOR type

# revision identifiers, used by Alembic.
revision: str = '6f3695ef31c6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_config_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_config_versions_created', 'agent_config_versions', ['created_at'], unique=False)
    op.create_table('cold_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('episode_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('stability_factor', sa.Float(), nullable=True),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('importance BETWEEN 0 AND 1', name='check_importance_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cold_memories_active', 'cold_memories', ['episode_type', 'importance'], unique=False, postgresql_where='expires_at IS NULL')
    op.create_index('idx_cold_memories_embedding', 'cold_memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_cold_memories_importance', 'cold_memories', ['importance'], unique=False)
    op.create_index('idx_cold_memories_tags', 'cold_memories', ['context_tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_cold_memories_type', 'cold_memories', ['episode_type'], unique=False)
    op.create_table('knowledge_entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'name', name='uq_entity_type_name')
    )
    op.create_index('idx_knowledge_entities_embedding', 'knowledge_entities', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_knowledge_entities_properties', 'knowledge_entities', ['properties'], unique=False, postgresql_using='gin')
    op.create_index('idx_knowledge_entities_type', 'knowledge_entities', ['entity_type'], unique=False)
    op.create_table('mutation_chains',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('parent_chain_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['parent_chain_id'], ['mutation_chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mutation_chains_parent', 'mutation_chains', ['parent_chain_id'], unique=False)
    op.create_index('idx_mutation_chains_status', 'mutation_chains', ['status'], unique=False, postgresql_where="status IN ('pending', 'in_progress')")
    op.create_index('idx_mutation_chains_trigger', 'mutation_chains', ['trigger_reason', 'created_at'], unique=False)
    op.create_table('task_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Text(), nullable=False),
    sa.Column('goal_text', sa.Text(), nullable=False),
    sa.Column('goal_priority', sa.SmallInteger(), nullable=False),
    sa.Column('strategy', sa.Text(), nullable=False),
    sa.Column('complexity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('goal_priority BETWEEN 1 AND 10', name='check_goal_priority_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_executions_created', 'task_executions', ['created_at'], unique=False)
    op.create_index('idx_task_executions_status', 'task_executions', ['status'], unique=False)
    op.create_index('idx_task_executions_thread', 'task_executions', ['thread_id'], unique=False)
    op.create_index(op.f('ix_task_executions_thread_id'), 'task_executions', ['thread_id'], unique=False)
    op.create_table('config_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_version_id', sa.Uuid(), nullable=False),
    sa.Column('key_path', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['config_version_id'], ['agent_config_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_snapshots_key', 'config_snapshots', ['key_path', 'created_at'], unique=False)
    op.create_index('idx_config_snapshots_version', 'config_snapshots', ['config_version_id'], unique=False)
    op.create_table('cost_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_ledger_date', 'cost_ledger', ['created_at'], unique=False)
    op.create_index('idx_cost_ledger_provider', 'cost_ledger', ['provider', 'model', 'created_at'], unique=False)
    op.create_index('idx_cost_ledger_task', 'cost_ledger', ['task_id', 'created_at'], unique=False)
    op.create_table('entity_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('strength BETWEEN 0 AND 1', name='check_strength_range'),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['knowledge_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relation_type', name='uq_entity_relation')
    )
    op.create_index('idx_entity_relations_source', 'entity_relations', ['source_id', 'relation_type'], unique=False)
    op.create_index('idx_entity_relations_strength', 'entity_relations', ['relation_type', 'strength'], unique=False, postgresql_where='strength > 0.7')
    op.create_index('idx_entity_relations_target', 'entity_relations', ['target_id', 'relation_type'], unique=False)
    op.create_table('evolution_telemetry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['mutation_chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evolution_telemetry_chain', 'evolution_telemetry', ['chain_id', 'created_at'], unique=False)
    op.create_index('idx_evolution_telemetry_type', 'evolution_telemetry', ['event_type', 'created_at'], unique=False)
    op.create_table('execution_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_execution_steps_failed', 'execution_steps', ['task_id'], unique=False, postgresql_where="status = 'failed'")
    op.create_index('idx_execution_steps_phase', 'execution_steps', ['phase'], unique=False)
    op.create_index('idx_execution_steps_task_number', 'execution_steps', ['task_id', 'step_number'], unique=False)
    op.create_table('mutations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chain_id', sa.Uuid(), nullable=False),
    sa.Column('mutation_type', sa.Text(), nullable=False),
    sa.Column('target_path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('mutated_content', sa.Text(), nullable=False),
    sa.Column('diff_content', sa.Text(), nullable=True),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['mutation_chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mutations_chain', 'mutations', ['chain_id', 'created_at'], unique=False)
    op.create_index('idx_mutations_pending', 'mutations', ['chain_id'], unique=False, postgresql_where="status IN ('generated', 'approved')")
    op.create_index('idx_mutations_type', 'mutations', ['mutation_type'], unique=False)
    op.create_table('warm_memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_task_id', sa.Uuid(), nullable=True),
    sa.Column('fitness_score', sa.Float(), nullable=False),
    sa.Column('access_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fitness_score BETWEEN 0 AND 1', name='check_fitness_score_range'),
    sa.ForeignKeyConstraint(['source_task_id'], ['task_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_warm_memories_active', 'warm_memories', ['memory_type', 'fitness_score'], unique=False, postgresql_where='expires_at IS NULL')
    op.create_index('idx_warm_memories_fitness', 'warm_memories', ['fitness_score'], unique=False, postgresql_where='fitness_score > 0.7')
    op.create_index('idx_warm_memories_tags', 'warm_memories', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_warm_memories_type', 'warm_memories', ['memory_type'], unique=False)
    op.create_table('ab_test_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mutation_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sa.Text(), nullable=False),
    sa.Column('control_value', sa.Float(), nullable=True),
    sa.Column('treatment_value', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mutation_id'], ['mutations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ab_test_results_metric', 'ab_test_results', ['metric_name', 'created_at'], unique=False)
    op.create_index('idx_ab_test_results_mutation', 'ab_test_results', ['mutation_id'], unique=False)
    op.create_index('idx_ab_test_results_significant', 'ab_test_results', ['metric_name'], unique=False, postgresql_where='is_significant = true')
    op.create_table('code_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mutation_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('version_hash', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('deployed', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mutation_id'], ['mutations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_code_versions_deployed', 'code_versions', ['file_path', 'deployed_at'], unique=False, postgresql_where='deployed = true')
    op.create_index('idx_code_versions_mutation', 'code_versions', ['mutation_id'], unique=False)
    op.create_index('idx_code_versions_path', 'code_versions', ['file_path', 'created_at'], unique=False)
    op.create_index('idx_code_versions_rollback', 'code_versions', ['file_path', 'created_at'], unique=False, postgresql_where='rolled_back = false')
    op.create_table('feedback_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='check_rating_range'),
    sa.ForeignKeyConstraint(['step_id'], ['execution_steps.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_events_task', 'feedback_events', ['task_id', 'created_at'], unique=False)
    op.create_index('idx_feedback_events_type', 'feedback_events', ['event_type'], unique=False)
    op.create_table('memory_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['warm_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_embeddings_model', 'memory_embeddings', ['embedding_model'], unique=False)
    op.create_index('idx_memory_embeddings_vector', 'memory_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('skill_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('memory_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=False),
    sa.Column('test_content', sa.Text(), nullable=True),
    sa.Column('test_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['warm_memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'version', name='uq_skill_version')
    )
    op.create_index('idx_skill_versions_active', 'skill_versions', ['memory_id'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_skill_versions_history', 'skill_versions', ['memory_id', 'version'], unique=False)
    op.create_table('tool_registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_name', sa.Text(), nullable=False),
    sa.Column('tool_type', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_mutation_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_mutation_id'], ['mutations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_name')
    )
    op.create_index('idx_tool_registrations_active', 'tool_registrations', ['tool_name'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_tool_registrations_type', 'tool_registrations', ['tool_type'], unique=False)
    op.create_table('tool_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code_content', sa.Text(), nullable=False),
    sa.Column('test_content', sa.Text(), nullable=True),
    sa.Column('test_pass_rate', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tool_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'version', name='uq_tool_version')
    )
    op.create_index('idx_tool_versions_active', 'tool_versions', ['tool_id'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_tool_versions_history', 'tool_versions', ['tool_id', 'version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tool_versions_history', table_name='tool_versions')
    op.drop_index('idx_tool_versions_active', table_name='tool_versions', postgresql_where='is_active = true')
    op.drop_table('tool_versions')
    op.drop_index('idx_tool_registrations_type', table_name='tool_registrations')
    op.drop_index('idx_tool_registrations_active', table_name='tool_registrations', postgresql_where='is_active = true')
    op.drop_table('tool_registrations')
    op.drop_index('idx_skill_versions_history', table_name='skill_versions')
    op.drop_index('idx_skill_versions_active', table_name='skill_versions', postgresql_where='is_active = true')
    op.drop_table('skill_versions')
    op.drop_index('idx_memory_embeddings_vector', table_name='memory_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_memory_embeddings_model', table_name='memory_embeddings')
    op.drop_table('memory_embeddings')
    op.drop_index('idx_feedback_events_type', table_name='feedback_events')
    op.drop_index('idx_feedback_events_task', table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index('idx_code_versions_rollback', table_name='code_versions', postgresql_where='rolled_back = false')
    op.drop_index('idx_code_versions_path', table_name='code_versions')
    op.drop_index('idx_code_versions_mutation', table_name='code_versions')
    op.drop_index('idx_code_versions_deployed', table_name='code_versions', postgresql_where='deployed = true')
    op.drop_table('code_versions')
    op.drop_index('idx_ab_test_results_significant', table_name='ab_test_results', postgresql_where='is_significant = true')
    op.drop_index('idx_ab_test_results_mutation', table_name='ab_test_results')
    op.drop_index('idx_ab_test_results_metric', table_name='ab_test_results')
    op.drop_table('ab_test_results')
    op.drop_index('idx_warm_memories_type', table_name='warm_memories')
    op.drop_index('idx_warm_memories_tags', table_name='warm_memories', postgresql_using='gin')
    op.drop_index('idx_warm_memories_fitness', table_name='warm_memories', postgresql_where='fitness_score > 0.7')
    op.drop_index('idx_warm_memories_active', table_name='warm_memories', postgresql_where='expires_at IS NULL')
    op.drop_table('warm_memories')
    op.drop_index('idx_mutations_type', table_name='mutations')
    op.drop_index('idx_mutations_pending', table_name='mutations', postgresql_where="status IN ('generated', 'approved')")
    op.drop_index('idx_mutations_chain', table_name='mutations')
    op.drop_table('mutations')
    op.drop_index('idx_execution_steps_task_number', table_name='execution_steps')
    op.drop_index('idx_execution_steps_phase', table_name='execution_steps')
    op.drop_index('idx_execution_steps_failed', table_name='execution_steps', postgresql_where="status = 'failed'")
    op.drop_table('execution_steps')
    op.drop_index('idx_evolution_telemetry_type', table_name='evolution_telemetry')
    op.drop_index('idx_evolution_telemetry_chain', table_name='evolution_telemetry')
    op.drop_table('evolution_telemetry')
    op.drop_index('idx_entity_relations_target', table_name='entity_relations')
    op.drop_index('idx_entity_relations_strength', table_name='entity_relations', postgresql_where='strength > 0.7')
    op.drop_index('idx_entity_relations_source', table_name='entity_relations')
    op.drop_table('entity_relations')
    op.drop_index('idx_cost_ledger_task', table_name='cost_ledger')
    op.drop_index('idx_cost_ledger_provider', table_name='cost_ledger')
    op.drop_index('idx_cost_ledger_date', table_name='cost_ledger')
    op.drop_table('cost_ledger')
    op.drop_index('idx_config_snapshots_version', table_name='config_snapshots')
    op.drop_index('idx_config_snapshots_key', table_name='config_snapshots')
    op.drop_table('config_snapshots')
    op.drop_index(op.f('ix_task_executions_thread_id'), table_name='task_executions')
    op.drop_index('idx_task_executions_thread', table_name='task_executions')
    op.drop_index('idx_task_executions_status', table_name='task_executions')
    op.drop_index('idx_task_executions_created', table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index('idx_mutation_chains_trigger', table_name='mutation_chains')
    op.drop_index('idx_mutation_chains_status', table_name='mutation_chains', postgresql_where="status IN ('pending', 'in_progress')")
    op.drop_index('idx_mutation_chains_parent', table_name='mutation_chains')
    op.drop_table('mutation_chains')
    op.drop_index('idx_knowledge_entities_type', table_name='knowledge_entities')
    op.drop_index('idx_knowledge_entities_properties', table_name='knowledge_entities', postgresql_using='gin')
    op.drop_index('idx_knowledge_entities_embedding', table_name='knowledge_entities', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('knowledge_entities')
    op.drop_index('idx_cold_memories_type', table_name='cold_memories')
    op.drop_index('idx_cold_memories_tags', table_name='cold_memories', postgresql_using='gin')
    op.drop_index('idx_cold_memories_importance', table_name='cold_memories')
    op.drop_index('idx_cold_memories_embedding', table_name='cold_memories', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('idx_cold_memories_active', table_name='cold_memories', postgresql_where='expires_at IS NULL')
    op.drop_table('cold_memories')
    op.drop_index('idx_agent_config_versions_created', table_name='agent_config_versions')
    op.drop_table('agent_config_versions')
    # ### end Alembic commands ###
